object Dependencies {
    const val gradle = "com.android.tools.build:gradle:4.1.2"
    const val kotlin = "org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.30"

    const val kotlinJdk = "org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.4.10"
    const val coreKtx = "androidx.core:core-ktx:1.3.2"
    const val appCompat = "androidx.appcompat:appcompat:1.2.0"
    const val material = "com.google.android.material:material:1.3.0"
    const val navigationUI = "androidx.navigation:navigation-ui-ktx:2.3.1"
    const val navigationFragmentKtx = "androidx.navigation:navigation-fragment-ktx:2.3.1"
    const val chart = "com.github.PhilJay:MPAndroidChart:v3.1.0"
    const val rxJava = "io.reactivex.rxjava3:rxjava:3.0.0"
    const val rxKotlin = "io.reactivex.rxjava3:rxkotlin:3.0.0"
    const val rxAndroid = "io.reactivex.rxjava3:rxandroid:3.0.0"
    const val retrofit = "com.squareup.retrofit2:retrofit:2.9.0"
    const val retrofitRxJavaAdapter = "com.squareup.retrofit2:adapter-rxjava3:2.9.0"
    const val retrofitGsonAdapter = "com.squareup.retrofit2:converter-gson:2.9.0"
    const val multiDex = "com.android.support:multidex:1.0.3"
    const val viewModelKtx = "androidx.lifecycle:lifecycle-viewmodel-ktx:2.2.0"
    const val lottie = "com.airbnb.android:lottie:3.6.0"
    const val viewBindingDelegate = "com.github.kirich1409:viewbindingpropertydelegate-noreflection:1.4.4"
    const val dagger = "com.google.dagger:dagger:2.29.1"
    const val daggerCompiler = "com.google.dagger:dagger-compiler:2.29.1"

    const val fragmentTesting = "androidx.fragment:fragment-testing:1.3.0"
    const val leakCanary = "com.squareup.leakcanary:leakcanary-android:2.6"

    const val jUnit = "junit:junit:4.13.1"
    const val jUnitExt = "androidx.test.ext:junit:1.1.2"
    const val jUnitKtx = "androidx.test.ext:junit-ktx:1.1.2"
    const val mockK = "io.mockk:mockk:1.10.0"
    const val coreTesting = "android.arch.core:core-testing:1.1.1"
    const val espresso = "androidx.test.espresso:espresso-core:3.3.0"
}